-- ============================================================================
-- Discord Trading Bot - Complete Schema Setup in discord_trading Schema
-- ============================================================================
-- Purpose: Create fresh discord_trading schema with all tables
-- Project: apps-hub (Supabase)
-- Date: 2025-11-17
--
-- USAGE:
-- 1. Copy this entire file
-- 2. Go to Supabase apps-hub project → SQL Editor
-- 3. Paste and click "Run"
-- 4. Verify "Success" message
-- 5. Update Railway env: POSTGRES_SCHEMA=discord_trading
-- ============================================================================

-- ============================================================================
-- STEP 1: Create Schema
-- ============================================================================

CREATE SCHEMA IF NOT EXISTS discord_trading;

COMMENT ON SCHEMA discord_trading IS 'Discord Trading Bot application schema';

-- ============================================================================
-- STEP 2: Grant Permissions
-- ============================================================================

-- Grant USAGE on schema (required to access objects in it)
GRANT USAGE ON SCHEMA discord_trading TO postgres, anon, authenticated, service_role;

-- Grant permissions on all tables
GRANT ALL ON ALL TABLES IN SCHEMA discord_trading TO postgres, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA discord_trading TO authenticated, anon;

-- Grant permissions on sequences (for SERIAL, BIGSERIAL columns)
GRANT ALL ON ALL SEQUENCES IN SCHEMA discord_trading TO postgres, service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA discord_trading TO authenticated, anon;

-- Grant permissions on functions
GRANT ALL ON ALL FUNCTIONS IN SCHEMA discord_trading TO postgres, service_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA discord_trading TO authenticated, anon;

-- Set default privileges for future objects (important!)
ALTER DEFAULT PRIVILEGES IN SCHEMA discord_trading GRANT ALL ON TABLES TO postgres, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA discord_trading GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO authenticated, anon;

ALTER DEFAULT PRIVILEGES IN SCHEMA discord_trading GRANT ALL ON SEQUENCES TO postgres, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA discord_trading GRANT USAGE, SELECT ON SEQUENCES TO authenticated, anon;

ALTER DEFAULT PRIVILEGES IN SCHEMA discord_trading GRANT ALL ON FUNCTIONS TO postgres, service_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA discord_trading GRANT EXECUTE ON FUNCTIONS TO authenticated, anon;

-- ============================================================================
-- STEP 3: Create Tables
-- ============================================================================

-- Set search path for this session
SET search_path TO discord_trading, public;

-- ----------------------------------------------------------------------------
-- Trade Ideas Table
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS trade_ideas (
    id TEXT PRIMARY KEY,
    ticker TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    trade_type TEXT NOT NULL,
    direction TEXT NOT NULL,
    entry DECIMAL NOT NULL,
    stop DECIMAL NOT NULL,
    target DECIMAL NOT NULL,
    target2 DECIMAL,
    confidence INTEGER NOT NULL,
    rationale TEXT,
    edges_applied JSONB,
    risk_notes TEXT,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),

    -- Market context at time of generation
    spy_bias TEXT,
    atr_value DECIMAL,
    market_volatility TEXT,

    -- Metadata
    session_id TEXT,
    discord_user_id TEXT,
    discord_message_id TEXT
);

COMMENT ON TABLE trade_ideas IS 'Main table for trade ideas generated by the bot';

-- ----------------------------------------------------------------------------
-- Outcomes Table
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS outcomes (
    id SERIAL PRIMARY KEY,
    trade_id TEXT NOT NULL REFERENCES discord_trading.trade_ideas(id),
    actual_outcome TEXT NOT NULL,
    profit_loss_pct DECIMAL,
    profit_loss_r DECIMAL,
    close_price DECIMAL,
    close_timestamp TIMESTAMPTZ,
    exit_reason TEXT,
    notes TEXT,

    -- Performance metrics
    hold_duration_minutes INTEGER,
    slippage_pct DECIMAL,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE outcomes IS 'Trade outcomes and performance tracking';

-- ----------------------------------------------------------------------------
-- Weekly Modifications Table
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS modifications (
    id SERIAL PRIMARY KEY,
    week TEXT NOT NULL,
    start_date DATE,
    end_date DATE,

    -- Performance metrics for the week
    metrics JSONB NOT NULL,

    -- Suggested changes
    suggested_changes JSONB NOT NULL,

    -- Analysis
    patterns_identified TEXT,
    strengths TEXT,
    weaknesses TEXT,

    -- Status
    status TEXT DEFAULT 'pending',
    applied_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE modifications IS 'Weekly performance analysis and suggested modifications';

-- ----------------------------------------------------------------------------
-- Market Data Cache Table
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS market_data_cache (
    id SERIAL PRIMARY KEY,
    cache_key TEXT UNIQUE NOT NULL,
    ticker TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    data JSONB NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE market_data_cache IS 'Cache for market data API responses';

-- ----------------------------------------------------------------------------
-- API Call Log Table
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS api_calls (
    id SERIAL PRIMARY KEY,
    api_name TEXT NOT NULL,
    endpoint TEXT,
    ticker TEXT,
    status_code INTEGER,
    success BOOLEAN,
    error_message TEXT,
    response_time_ms INTEGER,
    rate_limit_remaining INTEGER,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE api_calls IS 'Log of all external API calls for monitoring';

-- ----------------------------------------------------------------------------
-- System Events Log
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS system_events (
    id SERIAL PRIMARY KEY,
    event_type TEXT NOT NULL,
    component TEXT,
    message TEXT NOT NULL,
    details JSONB,
    severity TEXT DEFAULT 'info',
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE system_events IS 'System-wide event and error logging';

-- ============================================================================
-- STEP 4: Create Indexes
-- ============================================================================

-- Trade Ideas indexes
CREATE INDEX IF NOT EXISTS idx_trade_ideas_ticker ON trade_ideas(ticker);
CREATE INDEX IF NOT EXISTS idx_trade_ideas_status ON trade_ideas(status);
CREATE INDEX IF NOT EXISTS idx_trade_ideas_timestamp ON trade_ideas(timestamp);

-- Outcomes indexes
CREATE INDEX IF NOT EXISTS idx_outcomes_trade_id ON outcomes(trade_id);
CREATE INDEX IF NOT EXISTS idx_outcomes_timestamp ON outcomes(close_timestamp);

-- Market data cache indexes
CREATE INDEX IF NOT EXISTS idx_cache_key ON market_data_cache(cache_key);
CREATE INDEX IF NOT EXISTS idx_cache_expires ON market_data_cache(expires_at);

-- API calls indexes
CREATE INDEX IF NOT EXISTS idx_api_calls_timestamp ON api_calls(timestamp);

-- System events indexes
CREATE INDEX IF NOT EXISTS idx_system_events_timestamp ON system_events(timestamp);

-- ============================================================================
-- STEP 5: Create Views
-- ============================================================================

-- View: Recent Performance
CREATE OR REPLACE VIEW v_recent_performance AS
SELECT
    t.ticker,
    t.trade_type,
    t.direction,
    t.confidence,
    o.actual_outcome,
    o.profit_loss_r,
    o.close_timestamp,
    t.timestamp as entry_timestamp
FROM trade_ideas t
LEFT JOIN outcomes o ON t.id = o.trade_id
WHERE t.status = 'closed'
ORDER BY o.close_timestamp DESC;

COMMENT ON VIEW v_recent_performance IS 'Recent trading performance summary';

-- View: Win Rate by Ticker
CREATE OR REPLACE VIEW v_win_rate_by_ticker AS
SELECT
    t.ticker,
    COUNT(*) as total_trades,
    SUM(CASE WHEN o.actual_outcome = 'win' THEN 1 ELSE 0 END) as wins,
    SUM(CASE WHEN o.actual_outcome = 'loss' THEN 1 ELSE 0 END) as losses,
    ROUND(100.0 * SUM(CASE WHEN o.actual_outcome = 'win' THEN 1 ELSE 0 END) / COUNT(*), 2) as win_rate_pct,
    ROUND(AVG(o.profit_loss_r)::numeric, 2) as avg_r_multiple
FROM trade_ideas t
JOIN outcomes o ON t.id = o.trade_id
GROUP BY t.ticker
HAVING COUNT(*) >= 3;

COMMENT ON VIEW v_win_rate_by_ticker IS 'Win rate statistics by ticker (min 3 trades)';

-- View: API Health
CREATE OR REPLACE VIEW v_api_health AS
SELECT
    api_name,
    COUNT(*) as total_calls,
    SUM(CASE WHEN success = true THEN 1 ELSE 0 END) as successful_calls,
    ROUND(100.0 * SUM(CASE WHEN success = true THEN 1 ELSE 0 END) / COUNT(*), 2) as success_rate,
    ROUND(AVG(response_time_ms)::numeric, 2) as avg_response_ms
FROM api_calls
WHERE timestamp > NOW() - INTERVAL '24 hours'
GROUP BY api_name;

COMMENT ON VIEW v_api_health IS 'API health metrics for last 24 hours';

-- ============================================================================
-- STEP 6: Create Functions
-- ============================================================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION discord_trading.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION discord_trading.update_updated_at_column() IS 'Automatically updates updated_at column on row update';

-- ============================================================================
-- STEP 7: Create Triggers
-- ============================================================================

-- Trigger for trade_ideas updated_at
CREATE TRIGGER update_trade_ideas_updated_at
    BEFORE UPDATE ON trade_ideas
    FOR EACH ROW
    EXECUTE FUNCTION discord_trading.update_updated_at_column();

-- ============================================================================
-- STEP 8: Enable Row Level Security (Optional - for future)
-- ============================================================================

-- Currently allowing all access, can tighten later
-- Uncomment if you want RLS enabled:

-- ALTER TABLE trade_ideas ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE outcomes ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE modifications ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE market_data_cache ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE api_calls ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE system_events ENABLE ROW LEVEL SECURITY;

-- Create policies (example - adjust as needed):
-- CREATE POLICY "Allow all for service role" ON trade_ideas FOR ALL USING (auth.role() = 'service_role');

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================

-- Uncomment these to verify after running:

-- Check schema exists
-- SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'discord_trading';

-- Check all tables exist
-- SELECT table_name FROM information_schema.tables WHERE table_schema = 'discord_trading' ORDER BY table_name;

-- Check permissions
-- SELECT * FROM information_schema.role_table_grants WHERE table_schema = 'discord_trading' LIMIT 10;

-- ============================================================================
-- SUCCESS!
-- ============================================================================
-- If you see "Success. No rows returned" or similar, you're done!
--
-- NEXT STEPS:
-- 1. Go to Railway → discord-trading-bot → Variables
-- 2. Add: POSTGRES_SCHEMA=discord_trading
-- 3. Redeploy
-- 4. Test /health endpoint
--
-- The bot will now use the discord_trading schema automatically!
-- ============================================================================
