-- Phase II: Performance Tracking & Optimization System
-- Migration Script for Supabase PostgreSQL
-- Date: 2025-11-20
-- Schema: discord_trading

-- =====================================================================
-- PART 1: TRADE SIGNALS TABLE
-- Logs every trade signal generated by the bot
-- =====================================================================

CREATE TABLE IF NOT EXISTS trade_signals (
    -- Primary identification
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    trade_id VARCHAR(50) UNIQUE NOT NULL,  -- e.g., 'NVDA-20251120-001'
    ticker VARCHAR(10) NOT NULL,

    -- Trade setup
    trade_type VARCHAR(10) NOT NULL CHECK (trade_type IN ('day', 'swing')),
    direction VARCHAR(10) NOT NULL CHECK (direction IN ('long', 'short')),

    -- Price levels
    entry DECIMAL(10,2) NOT NULL,
    stop DECIMAL(10,2) NOT NULL,
    target DECIMAL(10,2) NOT NULL,
    target2 DECIMAL(10,2),  -- Optional second target

    -- Analysis details
    confidence INTEGER NOT NULL CHECK (confidence >= 0 AND confidence <= 5),
    edges JSONB,  -- Array of edge objects: [{"name": "Slope Filter", "applied": true, "value": 1.23}, ...]
    edges_count INTEGER DEFAULT 0,
    rationale TEXT,

    -- Timeframe signals (for analysis)
    timeframe_signals JSONB,  -- Store higher/middle/lower timeframe data

    -- Market context at signal generation
    atr_value DECIMAL(10,2),
    market_volatility VARCHAR(20),
    spy_bias VARCHAR(20),

    -- Status tracking
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'WIN', 'LOSS', 'EXPIRED', 'CANCELLED')),
    r_achieved DECIMAL(5,2),  -- Actual R-multiple if trade closed

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT NOW(),
    triggered_at TIMESTAMPTZ,  -- When price reached entry
    closed_at TIMESTAMPTZ,     -- When trade closed (hit target or stop)
    expires_at TIMESTAMPTZ,    -- Default: 7 days from creation for day trades, 30 days for swing

    -- Metadata
    sent_to_discord BOOLEAN DEFAULT TRUE,
    user_notes TEXT,
    flagged_for_review BOOLEAN DEFAULT FALSE,
    news_summary JSONB  -- Store relevant news at time of signal
);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_trade_signals_ticker ON trade_signals(ticker);
CREATE INDEX IF NOT EXISTS idx_trade_signals_status ON trade_signals(status);
CREATE INDEX IF NOT EXISTS idx_trade_signals_created_at ON trade_signals(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_trade_signals_confidence ON trade_signals(confidence);
CREATE INDEX IF NOT EXISTS idx_trade_signals_trade_type ON trade_signals(trade_type);
CREATE INDEX IF NOT EXISTS idx_trade_signals_expires_at ON trade_signals(expires_at) WHERE status = 'PENDING';

-- Add trigger for automatic expiry date calculation
CREATE OR REPLACE FUNCTION set_trade_expiry()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.expires_at IS NULL THEN
        IF NEW.trade_type = 'day' THEN
            NEW.expires_at = NEW.created_at + INTERVAL '7 days';
        ELSE
            NEW.expires_at = NEW.created_at + INTERVAL '30 days';
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trade_signals_set_expiry
    BEFORE INSERT ON trade_signals
    FOR EACH ROW
    EXECUTE FUNCTION set_trade_expiry();

-- =====================================================================
-- PART 2: EDGE PERFORMANCE MATERIALIZED VIEW
-- Tracks which edges perform best (updated periodically)
-- =====================================================================

CREATE MATERIALIZED VIEW IF NOT EXISTS edge_performance AS
SELECT
    edge->>'name' as edge_name,
    COUNT(*) as total_appearances,

    -- Win/Loss counts
    SUM(CASE WHEN status = 'WIN' THEN 1 ELSE 0 END) as wins,
    SUM(CASE WHEN status = 'LOSS' THEN 1 ELSE 0 END) as losses,
    SUM(CASE WHEN status = 'EXPIRED' THEN 1 ELSE 0 END) as expired,

    -- Win rate calculation (only closed trades)
    ROUND(
        (SUM(CASE WHEN status = 'WIN' THEN 1 ELSE 0 END)::DECIMAL /
         NULLIF(SUM(CASE WHEN status IN ('WIN','LOSS') THEN 1 ELSE 0 END), 0)) * 100,
        2
    ) as win_rate_pct,

    -- R-multiple statistics
    ROUND(AVG(CASE WHEN status IN ('WIN', 'LOSS') THEN r_achieved END)::numeric, 2) as avg_r_multiple,
    ROUND(MAX(CASE WHEN status IN ('WIN', 'LOSS') THEN r_achieved END)::numeric, 2) as max_r_multiple,
    ROUND(MIN(CASE WHEN status IN ('WIN', 'LOSS') THEN r_achieved END)::numeric, 2) as min_r_multiple,

    -- Confidence breakdown
    ROUND(AVG(CASE WHEN status IN ('WIN', 'LOSS') THEN confidence END)::numeric, 2) as avg_confidence,

    -- Last updated
    NOW() as last_updated

FROM trade_signals,
LATERAL jsonb_array_elements(edges) as edge
WHERE status IN ('WIN', 'LOSS', 'EXPIRED')
GROUP BY edge->>'name'
ORDER BY win_rate_pct DESC NULLS LAST, total_appearances DESC;

-- Create unique index for concurrent refresh
CREATE UNIQUE INDEX IF NOT EXISTS idx_edge_performance_name ON edge_performance(edge_name);

-- Function to refresh edge performance view
CREATE OR REPLACE FUNCTION refresh_edge_performance()
RETURNS void AS $$
BEGIN
    REFRESH MATERIALIZED VIEW CONCURRENTLY edge_performance;
END;
$$ LANGUAGE plpgsql;

-- =====================================================================
-- PART 3: WEEKLY REPORTS TABLE
-- Stores generated weekly analysis reports
-- =====================================================================

CREATE TABLE IF NOT EXISTS weekly_reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Week identification
    week_start DATE NOT NULL,
    week_end DATE NOT NULL,
    week_number VARCHAR(10) NOT NULL,  -- e.g., '2025-W47'

    -- Summary metrics
    total_trades INTEGER DEFAULT 0,
    total_wins INTEGER DEFAULT 0,
    total_losses INTEGER DEFAULT 0,
    total_expired INTEGER DEFAULT 0,
    total_pending INTEGER DEFAULT 0,

    -- Performance metrics
    win_rate DECIMAL(5,2),
    avg_r_multiple DECIMAL(5,2),
    total_r_achieved DECIMAL(7,2),  -- Sum of all R-multiples

    -- Best/Worst analysis
    best_edges JSONB,  -- Array of top 3 edges with stats
    worst_edges JSONB,  -- Array of bottom 3 edges with stats

    -- Breakdown by trade type
    day_trade_stats JSONB,   -- Stats for day trades only
    swing_trade_stats JSONB, -- Stats for swing trades only

    -- Confidence analysis
    confidence_breakdown JSONB,  -- Win rate by confidence level (1-5)

    -- Recommendations
    recommendations TEXT[],  -- Array of suggested improvements

    -- Full report data
    report_json JSONB,  -- Complete report with all details
    report_html TEXT,   -- Optional: HTML formatted report
    report_markdown TEXT,  -- Markdown formatted report

    -- Metadata
    created_at TIMESTAMPTZ DEFAULT NOW(),
    generated_by VARCHAR(50) DEFAULT 'automated',

    -- Make week unique
    CONSTRAINT unique_week_report UNIQUE (week_start, week_end)
);

-- Indexes for weekly reports
CREATE INDEX IF NOT EXISTS idx_weekly_reports_week_start ON weekly_reports(week_start DESC);
CREATE INDEX IF NOT EXISTS idx_weekly_reports_created_at ON weekly_reports(created_at DESC);

-- =====================================================================
-- PART 4: ADDITIONAL HELPER VIEWS
-- Useful queries for dashboard and analysis
-- =====================================================================

-- View: Recent Signals (Last 30 days)
CREATE OR REPLACE VIEW v_recent_signals AS
SELECT
    trade_id,
    ticker,
    trade_type,
    direction,
    entry,
    stop,
    target,
    confidence,
    edges_count,
    status,
    r_achieved,
    created_at,
    closed_at,
    EXTRACT(EPOCH FROM (COALESCE(closed_at, NOW()) - created_at))/3600 as hours_duration
FROM trade_signals
WHERE created_at > NOW() - INTERVAL '30 days'
ORDER BY created_at DESC;

-- View: Pending Trades (for outcome tracker)
CREATE OR REPLACE VIEW v_pending_trades AS
SELECT
    trade_id,
    ticker,
    trade_type,
    direction,
    entry,
    stop,
    target,
    target2,
    created_at,
    expires_at,
    CASE
        WHEN NOW() > expires_at THEN true
        ELSE false
    END as is_expired
FROM trade_signals
WHERE status = 'PENDING'
ORDER BY created_at DESC;

-- View: Performance Summary (All Time)
CREATE OR REPLACE VIEW v_performance_summary AS
SELECT
    COUNT(*) as total_signals,
    SUM(CASE WHEN status = 'WIN' THEN 1 ELSE 0 END) as total_wins,
    SUM(CASE WHEN status = 'LOSS' THEN 1 ELSE 0 END) as total_losses,
    SUM(CASE WHEN status = 'PENDING' THEN 1 ELSE 0 END) as total_pending,
    SUM(CASE WHEN status = 'EXPIRED' THEN 1 ELSE 0 END) as total_expired,

    ROUND(
        (SUM(CASE WHEN status = 'WIN' THEN 1 ELSE 0 END)::DECIMAL /
         NULLIF(SUM(CASE WHEN status IN ('WIN','LOSS') THEN 1 ELSE 0 END), 0)) * 100,
        2
    ) as win_rate_pct,

    ROUND(AVG(CASE WHEN status IN ('WIN', 'LOSS') THEN r_achieved END)::numeric, 2) as avg_r_multiple,
    ROUND(SUM(CASE WHEN status IN ('WIN', 'LOSS') THEN r_achieved ELSE 0 END)::numeric, 2) as total_r_achieved,

    ROUND(AVG(confidence)::numeric, 2) as avg_confidence,

    MIN(created_at) as first_signal_date,
    MAX(created_at) as last_signal_date
FROM trade_signals;

-- View: Confidence Performance
CREATE OR REPLACE VIEW v_confidence_performance AS
SELECT
    confidence,
    COUNT(*) as total_trades,
    SUM(CASE WHEN status = 'WIN' THEN 1 ELSE 0 END) as wins,
    SUM(CASE WHEN status = 'LOSS' THEN 1 ELSE 0 END) as losses,
    ROUND(
        (SUM(CASE WHEN status = 'WIN' THEN 1 ELSE 0 END)::DECIMAL /
         NULLIF(SUM(CASE WHEN status IN ('WIN','LOSS') THEN 1 ELSE 0 END), 0)) * 100,
        2
    ) as win_rate_pct,
    ROUND(AVG(CASE WHEN status IN ('WIN', 'LOSS') THEN r_achieved END)::numeric, 2) as avg_r_multiple
FROM trade_signals
WHERE status IN ('WIN', 'LOSS', 'EXPIRED')
GROUP BY confidence
ORDER BY confidence DESC;

-- View: Ticker Performance
CREATE OR REPLACE VIEW v_ticker_performance AS
SELECT
    ticker,
    COUNT(*) as total_trades,
    SUM(CASE WHEN status = 'WIN' THEN 1 ELSE 0 END) as wins,
    SUM(CASE WHEN status = 'LOSS' THEN 1 ELSE 0 END) as losses,
    ROUND(
        (SUM(CASE WHEN status = 'WIN' THEN 1 ELSE 0 END)::DECIMAL /
         NULLIF(SUM(CASE WHEN status IN ('WIN','LOSS') THEN 1 ELSE 0 END), 0)) * 100,
        2
    ) as win_rate_pct,
    ROUND(AVG(CASE WHEN status IN ('WIN', 'LOSS') THEN r_achieved END)::numeric, 2) as avg_r_multiple,
    MAX(created_at) as last_trade_date
FROM trade_signals
WHERE status IN ('WIN', 'LOSS', 'EXPIRED')
GROUP BY ticker
HAVING COUNT(*) >= 3  -- Only show tickers with 3+ trades
ORDER BY win_rate_pct DESC NULLS LAST, total_trades DESC;

-- =====================================================================
-- PART 5: HELPER FUNCTIONS
-- =====================================================================

-- Function to mark expired trades
CREATE OR REPLACE FUNCTION mark_expired_trades()
RETURNS TABLE(expired_count INTEGER) AS $$
BEGIN
    UPDATE trade_signals
    SET status = 'EXPIRED',
        closed_at = NOW()
    WHERE status = 'PENDING'
    AND NOW() > expires_at;

    GET DIAGNOSTICS expired_count = ROW_COUNT;
    RETURN QUERY SELECT expired_count;
END;
$$ LANGUAGE plpgsql;

-- Function to calculate R-multiple achieved
CREATE OR REPLACE FUNCTION calculate_r_multiple(
    p_direction VARCHAR,
    p_entry DECIMAL,
    p_stop DECIMAL,
    p_exit_price DECIMAL
) RETURNS DECIMAL AS $$
DECLARE
    risk DECIMAL;
    reward DECIMAL;
BEGIN
    IF p_direction = 'long' THEN
        risk = p_entry - p_stop;
        reward = p_exit_price - p_entry;
    ELSE
        risk = p_stop - p_entry;
        reward = p_entry - p_exit_price;
    END IF;

    IF risk = 0 THEN
        RETURN 0;
    END IF;

    RETURN ROUND((reward / risk)::numeric, 2);
END;
$$ LANGUAGE plpgsql;

-- =====================================================================
-- MIGRATION COMPLETE
-- =====================================================================

-- Print migration summary
DO $$
BEGIN
    RAISE NOTICE '=================================================';
    RAISE NOTICE 'Phase II Migration Complete!';
    RAISE NOTICE '=================================================';
    RAISE NOTICE 'Created:';
    RAISE NOTICE '  - trade_signals table';
    RAISE NOTICE '  - edge_performance materialized view';
    RAISE NOTICE '  - weekly_reports table';
    RAISE NOTICE '  - 5 helper views';
    RAISE NOTICE '  - 3 utility functions';
    RAISE NOTICE '  - 7 indexes';
    RAISE NOTICE '';
    RAISE NOTICE 'Next Steps:';
    RAISE NOTICE '  1. Update FastAPI to log trades to trade_signals';
    RAISE NOTICE '  2. Create outcome_tracker.py script';
    RAISE NOTICE '  3. Build Next.js analytics dashboard';
    RAISE NOTICE '  4. Create weekly_report_generator.py';
    RAISE NOTICE '=================================================';
END $$;
